DROP DATABASE IF EXISTS favorites_db;
CREATE DATABASE favorites_db;

USE favorites_db;
CREATE TABLE movies (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(50) NOT NULL,
  year INT NOT NULL
);

CREATE TABLE songs (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(50) NOT NULL,
  album VARCHAR(50) NOT NULL
);

CREATE TABLE foods (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
  cuisine VARCHAR(50) NOT NULL
);

CREATE TABLE games (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
  category VARCHAR(50) NOT NULL
);